parsers:
  javascript:
    enable_partials: yes # default yes
  v1:
    include_full_missed_files: true  # default false
 gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
